# Generated by Django 5.1.2 on 2024-11-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_member_id_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='User_id',
            new_name='user_id',
        ),
    ]
